# Generated by Django 4.2.13 on 2024-05-30 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meatshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('branch_name', models.CharField(blank=True, max_length=250, null=True)),
                ('branch_address', models.CharField(blank=True, max_length=250, null=True)),
                ('branch_image', models.ImageField(blank=True, null=True, upload_to='branch/image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
